import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/tag';

export const sample_foods: Food[] = [
    {
      id: '1',
      name: 'Jinny Dhosa',
      price: 5,
      cookTime: '15-20',
      favorite: true,
      origins: ['india', 'asia'],
      // stars: 3.0,
      imageUrl: '/assets/f-1.jpg',
      tags: ['South Indian', 'Soup'],
    },
    { 
      id: '2',
      name: 'Samosa',
      price: 2,
      cookTime: '30-35',
      favorite: true,
      origins: ['india', 'asia'],
      // stars: 3.0,
      imageUrl: '/assets/f-2.jpg',
      tags: ['FastFood', 'Soup'],
    },
    {
      id: '3',
      name: 'Daabeli',
      price: 1,
      cookTime: '15-20',
      favorite: false,
      origins: ['india', 'asia'],
      // stars: 3.0,
      imageUrl: '/assets/f-3.jpg',
      tags: ['FastFood', 'Soup'],
    },
    {
      id: '4',
      name: 'Dal Makhni',
      price: 4,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      // stars: 3.0,
      imageUrl: '/assets/f-4.jpg',
      tags: ['SlowFood', 'Soup'],
    },
    {
      id: '5',
      name: 'Thalipeeth',
      price: 3,
      cookTime: '30-35',
      favorite: false,
      origins: ['india', 'asia'],
      // stars: 3.0,
      imageUrl: '/assets/f-5.jpg',
      tags: ['SlowFood', 'Soup'],
    },
    {
      id: '6',
      name: 'Aam ras',
      price: 5,
      cookTime: '40-50',
      favorite: true,
      origins: ['india', 'asia'],
      // stars: 3.0,
      imageUrl: '/assets/f-6.jpg',
      tags: ['SlowFood', 'Soup','All'],
    },
    {
      id: '7',
      name: 'Undhiyu',
      price: 4,
      cookTime: '40-50',
      favorite: false,
      origins: ['india', 'asia'],
      // stars: 3.0,
      imageUrl: '/assets/f-7.jpg',
      tags: ['SlowFood', 'Soup'],
    },
    {
      id: '8',
      name: 'Cheese Masala Dhosa',
      price: 5,
      cookTime: '20-25',
      favorite: true,
      origins: ['india', 'asia'],
      // stars: 3.0,
      imageUrl: '/assets/f-8.jpg',
      tags: ['South Indian', 'Soup'],
    },
    {
    id:'9',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    // stars: 4.5,
    imageUrl: 'assets/f-9.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'10',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    // stars: 4.0,
    imageUrl: 'assets/f-11.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

export const sample_tags:Tag[]=[
  {name: 'All', count:6},
  {name: 'FastFood', count:4},
  {name: 'Pizza', count:2},
  {name: 'Lunch', count:3},
  {name: 'SlowFood', count:2},
  {name: 'Hamburger', count:1},
  {name: 'Fry', count:1},
  {name: 'Soup',count:1}
]
